services:
  spigot:
    build: spigot
    image: registry.gitlab.com/pineman/images/spigot:1.17-2
    container_name: spigot
    ports:
    - "25565:25565"
    volumes:
    - spigot:/spigot
    restart: unless-stopped

  spotifyd:
    build: spotifyd
    image: registry.gitlab.com/pineman/images/spotifyd:0.3.2-4
    container_name: spotifyd
    devices:
    - "/dev/snd:/dev/snd"
    command: -u 'joao.castropinheiro@gmail.com' -P 'echo $SPOTIFYD_PWD'
    restart: unless-stopped

  homepage_http:
    image: registry.gitlab.com/pineman/images/homepage-http:1.0.0-2
    container_name: hp_http
    environment:
      HP_DB_HOST: "services_homepage_db_1"
    ports:
    - "80:80"
    restart: unless-stopped

  homepage_db:
    image: registry.gitlab.com/pineman/images/homepage-db:1.0.0-2
    container_name: hp_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - "5432:5432"
    restart: unless-stopped

  abra:
    image: registry.gitlab.com/pineman/images/abra:1.0.0-1
    container_name: abra
    ports:
    - "2272:2272"
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - transmission-config:/config
      - /home/pineman/Downloads:/downloads
    restart: unless-stopped

volumes:
  spigot:
    name: spigot
  transmission-config:
    name: transmission-config
