x-common: &common
  restart: unless-stopped
  init: true
  logging:
    driver: journald
    options:
      tag: "{{.Name}}"

services:
  paper: &paper
    <<: *common
    build:
      context: paper
      cache_from: ["ghcr.io/pineman/services/paper:latest"]
      args: ["BUILDKIT_INLINE_CACHE=1"]
    image: ghcr.io/pineman/services/paper:1.19.2-1
    container_name: paper
    hostname: paper
    ports:
    - "25565:25565"
    volumes:
    - ./paper/server_mount:/paper
  paper-latest:
    <<: *paper
    image: ghcr.io/pineman/services/paper:latest
    profiles: ["push"]

  paper-primos: &paper-primos
    <<: *common
    build:
      context: paper-primos
      cache_from: ["ghcr.io/pineman/services/paper-primos:latest"]
      args: ["BUILDKIT_INLINE_CACHE=1"]
    image: ghcr.io/pineman/services/paper-primos:1.21.3-4
    container_name: paper-primos
    hostname: paper-primos
    ports:
    - "25565:25565"
    volumes:
    - ./paper-primos/server_mount:/paper-primos
  paper-primos-latest:
    <<: *paper-primos
    image: ghcr.io/pineman/services/paper-primos:latest
    profiles: ["push"]

  factorio: &factorio
    <<: *common
    build:
      context: factorio
      cache_from: ["ghcr.io/pineman/services/factorio:latest"]
      args: ["BUILDKIT_INLINE_CACHE=1"]
    image: ghcr.io/pineman/services/factorio:1.1.48-3
    container_name: factorio
    hostname: factorio
    ports:
    - "34197:34197/udp"
    volumes:
    - ./factorio/server_mount:/root/.factorio
  factorio-latest:
    <<: *factorio
    image: ghcr.io/pineman/services/factorio:latest
    profiles: ["push"]

  satisfactory: &satisfactory
    <<: *common
    image: wolveix/satisfactory-server:v1.2.4
    container_name: satisfactory
    hostname: satisfactory
    ports:
    - "7777:7777/udp"
    - "15000:15000/udp"
    - "15777:15777/udp"
    volumes:
    - ./satisfactory:/config
    environment:
    - MAXPLAYERS=2
    - PGID=1000
    - PUID=1000
    - AUTOSAVEINTERVAL=60
    - AUTOSAVENUM=10
    - AUTOPAUSE=false
