services:
  spigot:
    build: spigot
    image: docker.io/pineman/spigot:1.16.5
    container_name: spigot
    ports:
    - "25565:25565"
    volumes:
    - spigot:/spigot
    restart: unless-stopped
  spotifyd:
    build: spotifyd
    image: docker.io/pineman/spotifyd:0.3.2
    container_name: spotifyd
    devices:
    - "/dev/snd:/dev/snd"
    command: -u 'joao.castropinheiro@gmail.com' -P 'echo $SPOTIFYD_PWD'
    restart: unless-stopped

volumes:
  spigot:
    external:
      name: spigot
