x-common: &common
  restart: unless-stopped
  init: true
  # Due to various pitfalls such as https://github.com/moby/moby/issues/22054,
  # and performance.
  network_mode: host
  logging:
    driver: journald
    options:
      tag: "{{.Name}}"

services:
  paper: &paper
    <<: *common
    build:
      context: paper
      cache_from: ["registry.gitlab.com/pineman/services/paper:latest"]
      args: ["BUILDKIT_INLINE_CACHE=1"]
    image: registry.gitlab.com/pineman/services/paper:1.18.2-1
    container_name: paper
    ports:
    - "25565:25565"
    volumes:
    - /home/pineman/services/paper/server_mount:/paper
  paper-latest:
    <<: *paper
    image: registry.gitlab.com/pineman/services/paper:latest
    profiles: ["push"]

  factorio: &factorio
    <<: *common
    build:
      context: factorio
      cache_from: ["registry.gitlab.com/pineman/services/factorio:latest"]
      args: ["BUILDKIT_INLINE_CACHE=1"]
    image: registry.gitlab.com/pineman/services/factorio:1.1.48-3
    container_name: factorio
    ports:
    - "34197:34197/udp"
    volumes:
    - /home/pineman/services/factorio/server_mount:/root/.factorio
  factorio-latest:
    <<: *factorio
    image: registry.gitlab.com/pineman/services/factorio:latest
    profiles: ["push"]

