x-common: &common
  restart: unless-stopped
  init: true
  # Due to various pitfalls such as https://github.com/moby/moby/issues/22054,
  # and performance.
  network_mode: host
  logging:
    driver: journald
    options:
      tag: "{{.Name}}@{{.ImageID}}"

services:
  traefik: &traefik
    <<: *common
    build:
      context: traefik
      cache_from: ["registry.gitlab.com/pineman/services/traefik:latest"]
      args: ["BUILDKIT_INLINE_CACHE=1"]
    image: registry.gitlab.com/pineman/services/traefik:1.0.0
    container_name: traefik
    ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
    volumes:
    - /home/pineman/services/traefik/acme:/acme
  traefik-latest:
    <<: *traefik
    image: registry.gitlab.com/pineman/services/traefik:latest
    profiles: ["push"]

  homepage:
    <<: *common
    image: registry.gitlab.com/pineman/services/homepage:1.0.5
    container_name: homepage
    ports:
    - "8081:8081"

  abra:
    <<: *common
    image: registry.gitlab.com/pineman/services/abra:1.0.0-1
    container_name: abra
    ports:
    - "2272:2272"

  #ju:
  #  <<: *common
  #  image: registry.gitlab.com/pineman/services/ju:1.0.1
  #  container_name: ju
  #  ports:
  #  - "8082:8082"

  #paper: &paper
  #  <<: *common
  #  build:
  #    context: paper
  #    cache_from: ["registry.gitlab.com/pineman/services/paper:latest"]
  #    args: ["BUILDKIT_INLINE_CACHE=1"]
  #  image: registry.gitlab.com/pineman/services/paper:1.18.1-2
  #  container_name: paper
  #  ports:
  #  - "25565:25565"
  #  volumes:
  #  - /home/pineman/services/paper/server_mount:/paper
  #paper-latest:
  #  <<: *paper
  #  image: registry.gitlab.com/pineman/services/paper:latest
  #  profiles: ["push"]

  factorio: &factorio
    <<: *common
    build:
      context: factorio
      cache_from: ["registry.gitlab.com/pineman/services/factorio:latest"]
      args: ["BUILDKIT_INLINE_CACHE=1"]
    image: registry.gitlab.com/pineman/services/factorio:1.1.48-3
    container_name: factorio
    ports:
    - "34197:34197/udp"
    volumes:
    - /home/pineman/services/factorio/server_mount:/root/.factorio
  factorio-latest:
    <<: *factorio
    image: registry.gitlab.com/pineman/services/factorio:latest
    profiles: ["push"]

  transmission:
    <<: *common
    image: ghcr.io/linuxserver/transmission:version-3.00-r2
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - transmission-config:/config
      - /home/pineman/Downloads:/downloads

  grafana:
    <<: *common
    image: grafana/grafana:8.0.4-ubuntu
    container_name: grafana
    ports:
    - "3000:3000"

volumes:
  transmission-config:
    name: transmission-config
