services:
  spigot:
    build: spigot
    image: registry.gitlab.com/pineman/images/spigot:1.16.5-3
    container_name: spigot
    ports:
    - "25565:25565"
    volumes:
    - spigot:/spigot
    restart: unless-stopped

  spotifyd:
    build: spotifyd
    image: registry.gitlab.com/pineman/images/spotifyd:0.3.2-4
    container_name: spotifyd
    devices:
    - "/dev/snd:/dev/snd"
    command: -u 'joao.castropinheiro@gmail.com' -P 'echo $SPOTIFYD_PWD'
    restart: unless-stopped

  homepage_http:
    image: registry.gitlab.com/pineman/images/homepage-http:1.0.0-2
    container_name: hp_http
    environment:
      HP_DB_HOST: "services_homepage_db_1"
    ports:
    - "80:80"
    restart: unless-stopped

  homepage_db:
    image: registry.gitlab.com/pineman/images/homepage-db:1.0.0-2
    container_name: hp_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - "5432:5432"
    restart: unless-stopped

volumes:
  spigot:
    external:
      name: spigot
