services:
  homepage:
    image: registry.gitlab.com/pineman/images/homepage:1.0.0-2
    container_name: homepage
    ports:
    - "80:80"
    restart: unless-stopped

  abra:
    image: registry.gitlab.com/pineman/images/abra:1.0.0-1
    container_name: abra
    ports:
    - "2272:2272"
    restart: unless-stopped

  spigot: &spigot
    build:
      context: spigot
      cache_from: ["registry.gitlab.com/pineman/images/spigot:latest"]
      args: ["BUILDKIT_INLINE_CACHE=1"]
    image: registry.gitlab.com/pineman/images/spigot:1.17.1-3
    container_name: spigot
    ports:
    - "25565:25565"
    volumes:
    - spigot:/spigot
    restart: unless-stopped
  spigot-latest:
    <<: *spigot
    image: registry.gitlab.com/pineman/images/spigot:latest
    profiles: ["push"]

  spotifyd: &spotifyd
    build:
      context: spotifyd
      cache_from: ["registry.gitlab.com/pineman/images/spotifyd:latest"]
      args: ["BUILDKIT_INLINE_CACHE=1"]
    image: registry.gitlab.com/pineman/images/spotifyd:0.3.2-5
    container_name: spotifyd
    devices:
    - "/dev/snd:/dev/snd"
    command: -u 'joao.castropinheiro@gmail.com' -P 'echo $SPOTIFYD_PWD'
    restart: unless-stopped
  spotifyd-latest:
    <<: *spotifyd
    image: registry.gitlab.com/pineman/images/spotifyd:latest
    profiles: ["push"]

  transmission:
    image: ghcr.io/linuxserver/transmission:version-3.00-r2
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - transmission-config:/config
      - /home/pineman/Downloads:/downloads
    restart: unless-stopped

  # TODO: node_exporter
  # TODO: configs
  prometheus:
    image: docker.io/prom/prometheus:v2.28.1
    container_name: prometheus
    ports:
    - "9090:9090"
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana:8.0.4-ubuntu
    container_name: grafana
    ports:
    - "3000:3000"
    restart: unless-stopped

volumes:
  spigot:
    name: spigot
  transmission-config:
    name: transmission-config
