# Dynamic configuration
http:
  routers:
    homepage:
      rule: "Host(`www.pineman.eu`) || Host(`pineman.eu`)"
      entryPoints: https
      service: homepage
      tls:
        certResolver: pinecone
    abra:
      rule: "Host(`abra.pineman.eu`)"
      entryPoints: https
      service: abra
      tls:
        certResolver: pinecone
  services:
    homepage:
      loadBalancer:
        servers:
        - url: "http://localhost:8081"
    abra:
      loadBalancer:
        servers:
        - url: "http://localhost:2272"
