# Static configuration
accesslog: true

api:
  insecure: true

entryPoints:
  https:
    address: ":443"
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

certificatesResolvers:
  pinecone:
    acme:
      httpchallenge:
        entryPoint: http
      email: joao.castropinheiro@gmail.com
      storage: /acme/acme.json

providers:
  file:
    filename: /etc/traefik/routes.yaml
